version: '3.8'

services:
  flask_api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - AWS_LAMBDA_FUNCTION_NAME=flask-app-local
      - MYSQL_HOST=example.rds.com
      - MYSQL_USER=sample_user
      - MYSQL_PASSWORD=sample_password
      - MYSQL_DB=sample_database
    volumes:
      - .:/var/task